set(_CATKIN_CURRENT_PACKAGE "pose_for_gpu")
set(pose_for_gpu_VERSION "0.0.0")
set(pose_for_gpu_MAINTAINER "arnab <arnab@todo.todo>")
set(pose_for_gpu_PACKAGE_FORMAT "1")
set(pose_for_gpu_BUILD_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "nav_msgs" "sensor_msgs" "tf" "trajectory_msgs" "roscpp")
set(pose_for_gpu_BUILD_EXPORT_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "nav_msgs" "sensor_msgs" "tf" "trajectory_msgs" "roscpp")
set(pose_for_gpu_BUILDTOOL_DEPENDS "catkin")
set(pose_for_gpu_BUILDTOOL_EXPORT_DEPENDS )
set(pose_for_gpu_EXEC_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "nav_msgs" "sensor_msgs" "tf" "trajectory_msgs" "roscpp")
set(pose_for_gpu_RUN_DEPENDS "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "nav_msgs" "sensor_msgs" "tf" "trajectory_msgs" "roscpp")
set(pose_for_gpu_TEST_DEPENDS )
set(pose_for_gpu_DOC_DEPENDS )
set(pose_for_gpu_URL_WEBSITE "")
set(pose_for_gpu_URL_BUGTRACKER "")
set(pose_for_gpu_URL_REPOSITORY "")
set(pose_for_gpu_DEPRECATED "")